### ISSUE TITLE
请问如何编译成arm64设备的版本呢，直接下载发布的arm版本在设备上运行报错。

### ISSUE THREAD

**Issue by findziliao** [YaoApp/yao#107]

**Comment by findziliao** [comment]
panic: {"message":"获取可用端口失败 lookup localhost: device or resource busy","code":500,"context":null}

goroutine 1 [running]:
github.com/yaoapp/kun/exception.Exception.Throw(...)
        /home/runner/work/yao/kun/exception/exception.go:111
github.com/yaoapp/yao/network.FreePort()
        /home/runner/work/yao/yao/network/ip.go:46 +0x2c8
github.com/yaoapp/yao/share.init.0()
        /home/runner/work/yao/yao/share/session.go:27 +0x20

**Comment by findziliao** [comment]
交叉编译不了arm64版本，最后只好在arm设备上编译
