### ISSUE TITLE
把数据库改成MySQL后，运行yao migrate报错。

### ISSUE THREAD

**Issue by Earchaut** [YaoApp/yao#112]
yao init后修改.env文件，把数据库改成MySQL后，运行yao migrate报错。
系统CentOS8.2，运行Yao v0.9.2版本（v0.9.1版本根本运行不起来，init就报错）

fatal error: unexpected signal during runtime execution
[signal SIGSEGV: segmentation violation code=0x1 addr=0x63 pc=0x7fcb78bd3a30]

runtime stack:
runtime.throw({0x25b1b98, 0x7ffd6f007420})
	/opt/hostedtoolcache/go/1.17.8/x64/src/runtime/panic.go:1198 +0x71
runtime.sigpanic()
	/opt/hostedtoolcache/go/1.17.8/x64/src/runtime/signal_unix.go:719 +0x396

goroutine 12 [syscall]:
runtime.cgocall(0x11e2330, 0xc00005dd90)
	/opt/hostedtoolcache/go/1.17.8/x64/src/runtime/cgocall.go:156 +0x5c fp=0xc00005dd68 sp=0xc00005dd30 pc=0x41263c
net._C2func_getaddrinfo(0xc000405ab0, 0x0, 0xc0002877d0, 0xc000012650)
	_cgo_gotypes.go:90 +0x56 fp=0xc00005dd90 sp=0xc00005dd68 pc=0x56b676
net.cgoLookupIPCNAME.func1({0xc000405ab0, 0x0, 0x0}, 0xc0000942c2, 0xc00005de50)
	/opt/hostedtoolcache/go/1.17.8/x64/src/net/cgo_unix.go:163 +0x9f fp=0xc00005dde8 sp=0xc00005dd90 pc=0x56d3bf
net.cgoLookupIPCNAME({0xc0000942be, 0x3}, {0xc0000942c2, 0xc00005dfd0})
	/opt/hostedtoolcache/go/1.17.8/x64/src/net/cgo_unix.go:163 +0x16d fp=0xc00005df38 sp=0xc00005dde8 pc=0x56cc0d
net.cgoIPLookup(0x45f48b0, {0xc0000942be, 0xc0004058b0}, {0xc0000942c2, 0x0})
	/opt/hostedtoolcache/go/1.17.8/x64/src/net/cgo_unix.go:220 +0x3b fp=0xc00005dfa8 sp=0xc00005df38 pc=0x56d47b
net.cgoLookupIP·dwrap·25()
	/opt/hostedtoolcache/go/1.17.8/x64/src/net/cgo_unix.go:230 +0x36 fp=0xc00005dfe0 sp=0xc00005dfa8 pc=0x56d8f6
runtime.goexit()
	/opt/hostedtoolcache/go/1.17.8/x64/src/runtime/asm_amd64.s:1581 +0x1 fp=0xc00005dfe8 sp=0xc00005dfe0 pc=0x475361
created by net.cgoLookupIP
	/opt/hostedtoolcache/go/1.17.8/x64/src/net/cgo_unix.go:230 +0x125

goroutine 1 [chan receive]:
github.com/yaoapp/xun/capsule.(*Manager).AddConnection(0xc0001b82a0, {0x2579fa5, 0x7}, {0xc0002ab29e, 0x5}, {0xc0000942af, 0x4f}, 0x0, {0xc000439958, 0x1, ...})
	/home/runner/work/yao/xun/capsule/capsule.go:91 +0x2e9
github.com/yaoapp/xun/capsule.(*Manager).AddConn(...)
	/home/runner/work/yao/xun/capsule/capsule.go:45
github.com/yaoapp/xun/capsule.AddConn({0x2579fa5, 0x7}, {0xc0002ab29e, 0x5}, {0xc0000942af, 0x4f}, {0xc000439958, 0x1, 0x1})
	/home/runner/work/yao/xun/capsule/capsule.go:40 +0x150
github.com/yaoapp/yao/share.DBConnect({{0xc0002ab29e, 0x5}, {0xc0001e0ad0, 0x1, 0x1}, {0x0, 0x0, 0x0}, {0x0, 0x0}})
	/home/runner/work/yao/yao/share/db.go:15 +0x14e
github.com/yaoapp/yao/engine.Load({{0x257f638, 0xb}, {0xc0004c4ec9, 0x11}, {0xc000404779, 0x7}, 0x13eb, {0x0, 0x0}, {0x0, ...}, ...})
	/home/runner/work/yao/yao/engine/load.go:42 +0x15f
github.com/yaoapp/yao/cmd.glob..func4(0x432df40, {0x256f3fc, 0x0, 0x0})
	/home/runner/work/yao/yao/cmd/migrate.go:38 +0xb8
github.com/spf13/cobra.(*Command).execute(0x432df40, {0x464f288, 0x0, 0x0})
	/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.2.1/command.go:860 +0x5f8
github.com/spf13/cobra.(*Command).ExecuteC(0x432e1c0)
	/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.2.1/command.go:974 +0x3bc
github.com/spf13/cobra.(*Command).Execute(...)
	/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.2.1/command.go:902
github.com/yaoapp/yao/cmd.Execute()
	/home/runner/work/yao/yao/cmd/root.go:103 +0x25
main.main()
	/home/runner/work/yao/yao/main.go:13 +0x17

goroutine 9 [select]:
database/sql.(*DB).connectionOpener(0xc0003829c0, {0x2d5bdf8, 0xc0002bbf00})
	/opt/hostedtoolcache/go/1.17.8/x64/src/database/sql/sql.go:1196 +0x93
created by database/sql.OpenDB
	/opt/hostedtoolcache/go/1.17.8/x64/src/database/sql/sql.go:794 +0x188

goroutine 10 [select]:
net.(*Resolver).lookupIPAddr(0x45f48a0, {0x2d5be68, 0xc0001f61e0}, {0xc0000942be, 0x0}, {0xc0000942c2, 0x9})
	/opt/hostedtoolcache/go/1.17.8/x64/src/net/lookup.go:302 +0x5c7
net.(*Resolver).internetAddrList(0x2d5be68, {0x2d5be68, 0xc0001f61e0}, {0xc0000942be, 0x3}, {0xc0000942c2, 0xe})
	/opt/hostedtoolcache/go/1.17.8/x64/src/net/ipsock.go:288 +0x67a
net.(*Resolver).resolveAddrList(0x464f288, {0x2d5be68, 0xc0001f61e0}, {0x256f2d4, 0x4}, {0xc0000942be, 0x0}, {0xc0000942c2, 0xe}, {0x0, ...})
	/opt/hostedtoolcache/go/1.17.8/x64/src/net/dial.go:221 +0x41b
net.(*Dialer).DialContext(0xc000c93c88, {0x2d5be68, 0xc0001f61e0}, {0xc0000942be, 0x0}, {0xc0000942c2, 0x41caaf})
	/opt/hostedtoolcache/go/1.17.8/x64/src/net/dial.go:406 +0x448
github.com/go-sql-driver/mysql.(*connector).Connect(0xc000012630, {0x2d5be68, 0xc0001f61e0})
	/home/runner/go/pkg/mod/github.com/go-sql-driver/mysql@v1.6.0/connector.go:49 +0x345
database/sql.(*DB).conn(0xc0003829c0, {0x2d5be68, 0xc0001f61e0}, 0x1)
	/opt/hostedtoolcache/go/1.17.8/x64/src/database/sql/sql.go:1364 +0x7ac
database/sql.(*DB).PingContext(0x0, {0x2d5be68, 0xc0001f61e0})
	/opt/hostedtoolcache/go/1.17.8/x64/src/database/sql/sql.go:853 +0x7a
github.com/yaoapp/xun/capsule.(*Manager).AddConnection.func1()
	/home/runner/work/yao/xun/capsule/capsule.go:84 +0x47
created by github.com/yaoapp/xun/capsule.(*Manager).AddConnection
	/home/runner/work/yao/xun/capsule/capsule.go:83 +0x2cf

goroutine 11 [select]:
net.cgoLookupIP({0x2d5bdf8, 0xc0002bbf80}, {0xc0000942be, 0x9}, {0xc0000942c2, 0x0})
	/opt/hostedtoolcache/go/1.17.8/x64/src/net/cgo_unix.go:231 +0x1b7
net.(*Resolver).lookupIP(0x45f48a0, {0x2d5bdf8, 0xc0002bbf80}, {0xc0000942be, 0x3}, {0xc0000942c2, 0x9})
	/opt/hostedtoolcache/go/1.17.8/x64/src/net/lookup_unix.go:97 +0x128
net.glob..func1({0x2d5bdf8, 0xc0002bbf80}, 0x0, {0xc0000942be, 0x0}, {0xc0000942c2, 0xc99d5a})
	/opt/hostedtoolcache/go/1.17.8/x64/src/net/hook.go:23 +0x3d
net.(*Resolver).lookupIPAddr.func1()
	/opt/hostedtoolcache/go/1.17.8/x64/src/net/lookup.go:296 +0x9f
internal/singleflight.(*Group).doCall(0x45f48b0, 0xc0004b19f0, {0xc0004058b0, 0xd}, 0x0)
	/opt/hostedtoolcache/go/1.17.8/x64/src/internal/singleflight/singleflight.go:95 +0x3b
created by internal/singleflight.(*Group).DoChan
	/opt/hostedtoolcache/go/1.17.8/x64/src/internal/singleflight/singleflight.go:88 +0x2f1

**Comment by trheyi** [comment]
https://release-sv-1252011659.cos.na-siliconvalley.myqcloud.com/archives/yao-0.9.2-linux-amd64  Linux 
https://release-sv-1252011659.cos.na-siliconvalley.myqcloud.com/archives/yao-0.9.2-darwin-amd64 MacOS Inter
https://release-sv-1252011659.cos.na-siliconvalley.myqcloud.com/archives/yao-0.9.2-darwin-arm64  MacOS M1
用这个制品试试，这个问题新版已经修复。
