### ISSUE TITLE
Install error

### ISSUE THREAD

**Issue by gridworkz** [YaoApp/yao#127]
Installing on a fresh Ubuntu 22.04 gives the following error:
```
Mirror: https://release-sv.yaoapps.com/archives/yao-0.9.1-linux-amd64
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 88.1M  100 88.1M    0     0  1675k      0  0:00:53  0:00:53 --:--:-- 1767k
Installed: /usr/local/bin/yao
fatal error: unexpected signal during runtime execution
[signal SIGSEGV: segmentation violation code=0x1 addr=0x63 pc=0x7f3b8d5f9c74]

runtime stack:
runtime.throw({0x2594bdf, 0x0})
	/opt/hostedtoolcache/go/1.17.7/x64/src/runtime/panic.go:1198 +0x71
runtime.sigpanic()
	/opt/hostedtoolcache/go/1.17.7/x64/src/runtime/signal_unix.go:719 +0x396

goroutine 9 [syscall]:
runtime.cgocall(0x11ca250, 0xc00005bd90)
	/opt/hostedtoolcache/go/1.17.7/x64/src/runtime/cgocall.go:156 +0x5c fp=0xc00005bd68 sp=0xc00005bd30 pc=0x41263c
net._C2func_getaddrinfo(0xc000436730, 0x0, 0xc0002ebec0, 0xc000010078)
	_cgo_gotypes.go:90 +0x56 fp=0xc00005bd90 sp=0xc00005bd68 pc=0x56ae76
net.cgoLookupIPCNAME.func1({0xc000436730, 0x0, 0x0}, 0x25634e0, 0xc00005be50)
	/opt/hostedtoolcache/go/1.17.7/x64/src/net/cgo_unix.go:163 +0x9f fp=0xc00005bde8 sp=0xc00005bd90 pc=0x56cbbf
net.cgoLookupIPCNAME({0x25521a2, 0x3}, {0x25634e0, 0x0})
	/opt/hostedtoolcache/go/1.17.7/x64/src/net/cgo_unix.go:163 +0x16d fp=0xc00005bf38 sp=0xc00005bde8 pc=0x56c40d
net.cgoIPLookup(0x45c7c30, {0x25521a2, 0xc000436500}, {0x25634e0, 0x0})
	/opt/hostedtoolcache/go/1.17.7/x64/src/net/cgo_unix.go:220 +0x3b fp=0xc00005bfa8 sp=0xc00005bf38 pc=0x56cc7b
net.cgoLookupIP·dwrap·25()
	/opt/hostedtoolcache/go/1.17.7/x64/src/net/cgo_unix.go:230 +0x36 fp=0xc00005bfe0 sp=0xc00005bfa8 pc=0x56d0f6
runtime.goexit()
	/opt/hostedtoolcache/go/1.17.7/x64/src/runtime/asm_amd64.s:1581 +0x1 fp=0xc00005bfe8 sp=0xc00005bfe0 pc=0x475361
created by net.cgoLookupIP
	/opt/hostedtoolcache/go/1.17.7/x64/src/net/cgo_unix.go:230 +0x125

goroutine 1 [select, locked to thread]:
net.(*Resolver).lookupIPAddr(0x45c7c20, {0x2d3a090, 0xc000040098}, {0x25521a2, 0xc0002eb350}, {0x25634e0, 0x9})
	/opt/hostedtoolcache/go/1.17.7/x64/src/net/lookup.go:302 +0x5c7
net.(*Resolver).internetAddrList(0xc00022fa78, {0x2d3a090, 0xc000040098}, {0x25521a2, 0x3}, {0x25634e0, 0xb})
	/opt/hostedtoolcache/go/1.17.7/x64/src/net/ipsock.go:288 +0x67a
net.ResolveTCPAddr({0x25521a2, 0x2a}, {0x25634e0, 0xb})
	/opt/hostedtoolcache/go/1.17.7/x64/src/net/tcpsock.go:77 +0xaf
github.com/yaoapp/yao/network.FreePort()
	/home/runner/work/yao/yao/network/ip.go:44 +0x65
github.com/yaoapp/yao/share.init.0()
	/home/runner/work/yao/yao/share/session.go:27 +0x19

goroutine 8 [select]:
net.cgoLookupIP({0x2d3a058, 0xc000081e40}, {0x25521a2, 0x9}, {0x25634e0, 0x0})
	/opt/hostedtoolcache/go/1.17.7/x64/src/net/cgo_unix.go:231 +0x1b7
net.(*Resolver).lookupIP(0x45c7c20, {0x2d3a058, 0xc000081e40}, {0x25521a2, 0x3}, {0x25634e0, 0x9})
	/opt/hostedtoolcache/go/1.17.7/x64/src/net/lookup_unix.go:97 +0x128
net.glob..func1({0x2d3a058, 0xc000081e40}, 0x0, {0x25521a2, 0x0}, {0x25634e0, 0x0})
	/opt/hostedtoolcache/go/1.17.7/x64/src/net/hook.go:23 +0x3d
net.(*Resolver).lookupIPAddr.func1()
	/opt/hostedtoolcache/go/1.17.7/x64/src/net/lookup.go:296 +0x9f
internal/singleflight.(*Group).doCall(0x45c7c30, 0xc00041c140, {0xc000436500, 0xd}, 0x0)
	/opt/hostedtoolcache/go/1.17.7/x64/src/internal/singleflight/singleflight.go:95 +0x3b
created by internal/singleflight.(*Group).DoChan
	/opt/hostedtoolcache/go/1.17.7/x64/src/internal/singleflight/singleflight.go:88 +0x2f1

Version: 

DONE
```
```
go version go1.16.2 linux/amd64
```

**Comment by gridworkz** [comment]
Edit: I built from scratch and all good now. Also upgraded to: ```go1.18beta1 linux/amd64```

**Comment by MatrixAge** [comment]
Looks like a problem with the environment。
