### ISSUE TITLE
yao init fail

### ISSUE THREAD

**Issue by mgholam** [YaoApp/yao#150]
On fedora 36, amd64

```sh
$ yao init

fatal error: unexpected signal during runtime execution
[signal SIGSEGV: segmentation violation code=0x1 addr=0x47 pc=0x7f3a8831f805]

runtime stack:
runtime.throw({0x2594bdf, 0x0})
	/opt/hostedtoolcache/go/1.17.7/x64/src/runtime/panic.go:1198 +0x71
runtime.sigpanic()
	/opt/hostedtoolcache/go/1.17.7/x64/src/runtime/signal_unix.go:719 +0x396

goroutine 12 [syscall]:
runtime.cgocall(0x11ca250, 0xc00049dd90)
	/opt/hostedtoolcache/go/1.17.7/x64/src/runtime/cgocall.go:156 +0x5c fp=0xc00049dd68 sp=0xc00049dd30 pc=0x41263c
net._C2func_getaddrinfo(0xc00048f8b0, 0x0, 0xc0003ca7b0, 0xc0004865b8)
	_cgo_gotypes.go:90 +0x56 fp=0xc00049dd90 sp=0xc00049dd68 pc=0x56ae76
net.cgoLookupIPCNAME.func1({0xc00048f8b0, 0x0, 0x0}, 0x25634e0, 0xc00049de50)
	/opt/hostedtoolcache/go/1.17.7/x64/src/net/cgo_unix.go:163 +0x9f fp=0xc00049dde8 sp=0xc00049dd90 pc=0x56cbbf
net.cgoLookupIPCNAME({0x25521a2, 0x3}, {0x25634e0, 0x0})
	/opt/hostedtoolcache/go/1.17.7/x64/src/net/cgo_unix.go:163 +0x16d fp=0xc00049df38 sp=0xc00049dde8 pc=0x56c40d
net.cgoIPLookup(0x45c7c30, {0x25521a2, 0xc00048f730}, {0x25634e0, 0x0})
	/opt/hostedtoolcache/go/1.17.7/x64/src/net/cgo_unix.go:220 +0x3b fp=0xc00049dfa8 sp=0xc00049df38 pc=0x56cc7b
net.cgoLookupIP·dwrap·25()
	/opt/hostedtoolcache/go/1.17.7/x64/src/net/cgo_unix.go:230 +0x36 fp=0xc00049dfe0 sp=0xc00049dfa8 pc=0x56d0f6
runtime.goexit()
	/opt/hostedtoolcache/go/1.17.7/x64/src/runtime/asm_amd64.s:1581 +0x1 fp=0xc00049dfe8 sp=0xc00049dfe0 pc=0x475361
created by net.cgoLookupIP
	/opt/hostedtoolcache/go/1.17.7/x64/src/net/cgo_unix.go:230 +0x125

goroutine 1 [select, locked to thread]:
net.(*Resolver).lookupIPAddr(0x45c7c20, {0x2d3a090, 0xc00013c000}, {0x25521a2, 0xc00038fa70}, {0x25634e0, 0x9})
	/opt/hostedtoolcache/go/1.17.7/x64/src/net/lookup.go:302 +0x5c7
net.(*Resolver).internetAddrList(0xc0004b3a78, {0x2d3a090, 0xc00013c000}, {0x25521a2, 0x3}, {0x25634e0, 0xb})
	/opt/hostedtoolcache/go/1.17.7/x64/src/net/ipsock.go:288 +0x67a
net.ResolveTCPAddr({0x25521a2, 0x2a}, {0x25634e0, 0xb})
	/opt/hostedtoolcache/go/1.17.7/x64/src/net/tcpsock.go:77 +0xaf
github.com/yaoapp/yao/network.FreePort()
	/home/runner/work/yao/yao/network/ip.go:44 +0x65
github.com/yaoapp/yao/share.init.0()
	/home/runner/work/yao/yao/share/session.go:27 +0x19

goroutine 11 [select]:
net.cgoLookupIP({0x2d3a058, 0xc0000a3980}, {0x25521a2, 0x9}, {0x25634e0, 0x0})
	/opt/hostedtoolcache/go/1.17.7/x64/src/net/cgo_unix.go:231 +0x1b7
net.(*Resolver).lookupIP(0x45c7c20, {0x2d3a058, 0xc0000a3980}, {0x25521a2, 0x3}, {0x25634e0, 0x9})
	/opt/hostedtoolcache/go/1.17.7/x64/src/net/lookup_unix.go:97 +0x128
net.glob..func1({0x2d3a058, 0xc0000a3980}, 0x0, {0x25521a2, 0x0}, {0x25634e0, 0x0})
	/opt/hostedtoolcache/go/1.17.7/x64/src/net/hook.go:23 +0x3d
net.(*Resolver).lookupIPAddr.func1()
	/opt/hostedtoolcache/go/1.17.7/x64/src/net/lookup.go:296 +0x9f
internal/singleflight.(*Group).doCall(0x45c7c30, 0xc000415130, {0xc00048f730, 0xd}, 0x0)
	/opt/hostedtoolcache/go/1.17.7/x64/src/internal/singleflight/singleflight.go:95 +0x3b
created by internal/singleflight.(*Group).DoChan
	/opt/hostedtoolcache/go/1.17.7/x64/src/internal/singleflight/singleflight.go:88 +0x2f1
```

**Comment by trheyi** [comment]
check the version of yao,  using `yao version` command.
the latest version should be  v0.9.2

https://release-sv-1252011659.cos.na-siliconvalley.myqcloud.com/archives/yao-0.9.2-linux-amd64

**Comment by mgholam** [comment]
Yes it is
```
$ yao version
0.9.2-aa4bc897251a
```

**Comment by trheyi** [comment]
update yao with the following link.  `FreePort()`  was  removed in this version
https://release-sv-1252011659.cos.na-siliconvalley.myqcloud.com/archives/yao-0.9.2-linux-amd64

**Comment by mgholam** [comment]
fixed
