### ISSUE TITLE
rockylinux下无法安装执行

### ISSUE THREAD

**Issue by WhatAKitty** [YaoApp/yao#51]
环境：rockylinux 8.5 64bit 
执行命令：`curl -fsSL https://website.yaoapps.com/install.sh | bash`
执行结果信息如下：
```
Installed: /usr/local/bin/yao
fatal error: unexpected signal during runtime execution
[signal SIGSEGV: segmentation violation code=0x1 addr=0x63 pc=0x7f09f030cbd0]

runtime stack:
runtime.throw({0x2594bdf, 0x7f09f16327c0})
	/opt/hostedtoolcache/go/1.17.7/x64/src/runtime/panic.go:1198 +0x71
runtime.sigpanic()
	/opt/hostedtoolcache/go/1.17.7/x64/src/runtime/signal_unix.go:719 +0x396

goroutine 36 [syscall]:
runtime.cgocall(0x11ca250, 0xc000133d90)
	/opt/hostedtoolcache/go/1.17.7/x64/src/runtime/cgocall.go:156 +0x5c fp=0xc000133d68 sp=0xc000133d30 pc=0x41263c
net._C2func_getaddrinfo(0xc000116160, 0x0, 0xc000059770, 0xc000114028)
	_cgo_gotypes.go:90 +0x56 fp=0xc000133d90 sp=0xc000133d68 pc=0x56ae76
net.cgoLookupIPCNAME.func1({0xc000116160, 0x0, 0x0}, 0x25634e0, 0xc000133e50)
	/opt/hostedtoolcache/go/1.17.7/x64/src/net/cgo_unix.go:163 +0x9f fp=0xc000133de8 sp=0xc000133d90 pc=0x56cbbf
net.cgoLookupIPCNAME({0x25521a2, 0x3}, {0x25634e0, 0x0})
	/opt/hostedtoolcache/go/1.17.7/x64/src/net/cgo_unix.go:163 +0x16d fp=0xc000133f38 sp=0xc000133de8 pc=0x56c40d
net.cgoIPLookup(0x45c7c30, {0x25521a2, 0xc000491580}, {0x25634e0, 0x0})
	/opt/hostedtoolcache/go/1.17.7/x64/src/net/cgo_unix.go:220 +0x3b fp=0xc000133fa8 sp=0xc000133f38 pc=0x56cc7b
net.cgoLookupIP·dwrap·25()
	/opt/hostedtoolcache/go/1.17.7/x64/src/net/cgo_unix.go:230 +0x36 fp=0xc000133fe0 sp=0xc000133fa8 pc=0x56d0f6
runtime.goexit()
	/opt/hostedtoolcache/go/1.17.7/x64/src/runtime/asm_amd64.s:1581 +0x1 fp=0xc000133fe8 sp=0xc000133fe0 pc=0x475361
created by net.cgoLookupIP
	/opt/hostedtoolcache/go/1.17.7/x64/src/net/cgo_unix.go:230 +0x125

goroutine 1 [select, locked to thread]:
net.(*Resolver).lookupIPAddr(0x45c7c20, {0x2d3a090, 0xc0000480c0}, {0x25521a2, 0xc0005a3aa0}, {0x25634e0, 0x9})
	/opt/hostedtoolcache/go/1.17.7/x64/src/net/lookup.go:302 +0x5c7
net.(*Resolver).internetAddrList(0xc000145a78, {0x2d3a090, 0xc0000480c0}, {0x25521a2, 0x3}, {0x25634e0, 0xb})
	/opt/hostedtoolcache/go/1.17.7/x64/src/net/ipsock.go:288 +0x67a
net.ResolveTCPAddr({0x25521a2, 0x2a}, {0x25634e0, 0xb})
	/opt/hostedtoolcache/go/1.17.7/x64/src/net/tcpsock.go:77 +0xaf
github.com/yaoapp/yao/network.FreePort()
	/home/runner/work/yao/yao/network/ip.go:44 +0x65
github.com/yaoapp/yao/share.init.0()
	/home/runner/work/yao/yao/share/session.go:27 +0x19

goroutine 7 [select]:
net.cgoLookupIP({0x2d3a058, 0xc0003e0100}, {0x25521a2, 0x9}, {0x25634e0, 0x0})
	/opt/hostedtoolcache/go/1.17.7/x64/src/net/cgo_unix.go:231 +0x1b7
net.(*Resolver).lookupIP(0x45c7c20, {0x2d3a058, 0xc0003e0100}, {0x25521a2, 0x3}, {0x25634e0, 0x9})
	/opt/hostedtoolcache/go/1.17.7/x64/src/net/lookup_unix.go:97 +0x128
net.glob..func1({0x2d3a058, 0xc0003e0100}, 0x0, {0x25521a2, 0x0}, {0x25634e0, 0x0})
	/opt/hostedtoolcache/go/1.17.7/x64/src/net/hook.go:23 +0x3d
net.(*Resolver).lookupIPAddr.func1()
	/opt/hostedtoolcache/go/1.17.7/x64/src/net/lookup.go:296 +0x9f
internal/singleflight.(*Group).doCall(0x45c7c30, 0xc0004a6c80, {0xc000491580, 0xd}, 0x0)
	/opt/hostedtoolcache/go/1.17.7/x64/src/internal/singleflight/singleflight.go:95 +0x3b
created by internal/singleflight.(*Group).DoChan
	/opt/hostedtoolcache/go/1.17.7/x64/src/internal/singleflight/singleflight.go:88 +0x2f1
Version: 
DONE

```

**Comment by trheyi** [comment]
rockylinux  的 /etc/hosts  中的配置是啥?

**Comment by WhatAKitty** [comment]
@trheyi 内容如下
127.0.0.1   localhost localhost.localdomain localhost4 localhost4.localdomain4
::1         localhost localhost.localdomain localhost6 localhost6.localdomain6

**Comment by andi-souwer** [comment]
用docker可以跑起来
