### ISSUE TITLE
默认init后的demo，执行yao start报错

### ISSUE THREAD

**Issue by tw93** [YaoApp/yao#67]
具体命令执行情况如下：
```
🏂 yao yao start            

---------------------------------
API List
---------------------------------

xiang.xiang(5)
GET /api/xiang/ping     process: xiang.main.Ping
POST /api/xiang/ping/post       process: xiang.main.Ping
GET /api/xiang/inspect  process: xiang.main.inspect
GET /api/xiang/menu     process: flows.xiang.menu
GET /api/xiang/favicon.ico      process: xiang.main.Favicon

xiang.chart(2)
GET /api/xiang/chart/:name/data         process: xiang.chart.Data
GET /api/xiang/chart/:name/setting      process: xiang.chart.Setting

xiang.table(12)
GET /api/xiang/table/:name/search       process: xiang.table.Search
GET /api/xiang/table/:name/find/:id     process: xiang.table.Find
GET /api/xiang/table/:name/select       process: xiang.table.Select
POST /api/xiang/table/:name/save        process: xiang.table.Save
POST /api/xiang/table/:name/quicksave   process: xiang.table.QuickSave
POST /api/xiang/table/:name/delete/:id  process: xiang.table.Delete
POST /api/xiang/table/:name/insert      process: xiang.table.Insert
POST /api/xiang/table/:name/delete/where        process: xiang.table.DeleteWhere
POST /api/xiang/table/:name/delete/in   process: xiang.table.DeleteIn
POST /api/xiang/table/:name/update/where        process: xiang.table.UpdateWhere
POST /api/xiang/table/:name/update/in   process: xiang.table.UpdateIn
GET /api/xiang/table/:name/setting      process: xiang.table.Setting

demo(1)
GET /api/demo/next      process: scripts.day.NextDay

xiang.storage(4)
POST /api/xiang/storage/upload  process: xiang.fs.Upload
GET /api/xiang/storage/readfile         process: xiang.fs.ReadFile
GET /api/xiang/storage/url      process: xiang.fs.GetURL
GET /api/xiang/storage/token    process: xiang.fs.GetToken

xiang.user(6)
GET /api/xiang/user/captcha     process: xiang.user.Captcha
POST /api/xiang/user/login      process: xiang.user.Login
POST /api/xiang/user/token      process: xiang.user.Token
GET /api/xiang/user/menu        process: flows.xiang.menu
GET /api/xiang/user/info        process: xiang.user.Info
GET /api/xiang/user/token/refresh       process: xiang.user.TokenRefresh

xiang.page(2)
GET /api/xiang/page/:name/data  process: xiang.page.Data
GET /api/xiang/page/:name/setting       process: xiang.page.Setting

xiang.import(6)
POST /api/xiang/import/:name    process: xiang.import.Run
GET /api/xiang/import/:name/setting     process: xiang.import.Setting
POST /api/xiang/import/:name/data       process: xiang.import.Data
GET /api/xiang/import/:name/data/setting        process: xiang.import.DataSetting
GET /api/xiang/import/:name/mapping     process: xiang.import.Mapping
GET /api/xiang/import/:name/mapping/setting     process: xiang.import.MappingSetting

---------------------------------
Yao  development
---------------------------------
Root  /Users/tw93/www/yao
Frontend  http://127.0.0.1:5099/
Dashboard  http://127.0.0.1:5099/xiang/login/admin
API  http://127.0.0.1:5099/api
SessionPort  49220
Listening  0.0.0.0:5099

✨LISTENING✨
Watching: /Users/tw93/www/yao/flows
Watching: /Users/tw93/www/yao/apis
Watching: /Users/tw93/www/yao/models
Watching: /Users/tw93/www/yao/tables
Watching: /Users/tw93/www/yao/libs
Watching: /Users/tw93/www/yao/scripts
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x68 pc=0x48692c5]

goroutine 68 [running]:
github.com/buraksezer/olric.(*Olric).Start(0x0)
        /Users/runner/go/pkg/mod/github.com/buraksezer/olric@v0.4.2/olric.go:353 +0xe5
github.com/yaoapp/yao/share.SessionServerStart.func2()
        /Users/runner/work/yao/yao/share/session.go:103 +0x2d
created by github.com/yaoapp/yao/share.SessionServerStart
        /Users/runner/work/yao/yao/share/session.go:102 +0x387
```

**Comment by iamdaiyuan** [comment]
数据库连接配置了吗

**Comment by trheyi** [comment]
SessionServer 的一个已知BUG，开发模式下偶发无法启动， 0.9.2 将替换掉 olric 这个包。 

换成 production 模式启动试试

**Comment by tw93** [comment]
@trheyi 试了试，我这边是必要，用的 mac 最新版本
go version go1.15.8 darwin/amd64

**Comment by trheyi** [comment]
是自己编译的? 还是0.9.1？ 看错误信息，是启动 session 服务器时报错，yao run <处理器> 是否可以正常工作？

**Comment by tw93** [comment]
```
🏂 yao yao run flows.setmenu
Run: flows.setmenu
--------------------------------------
flows.setmenu Response
--------------------------------------
"done"
--------------------------------------
✨DONE✨
 🏂 yao yao run models.pet.Get '::{}'
Run: models.pet.Get
args[0]: {}
--------------------------------------
models.pet.Get Response
--------------------------------------
[
    {
        "created_at": "2022-03-18 06:17:16",
        "deleted_at": null,
        "desc": "a cat",
        "id": 1,
        "kind": "cat",
        "name": "Cookie",
        "sn": "100001",
        "updated_at": null
    },
    {
        "created_at": "2022-03-18 06:17:16",
        "deleted_at": null,
        "desc": "a dog",
        "id": 2,
        "kind": "dog",
        "name": "Beibei",
        "sn": "100002",
        "updated_at": null
    }
]
--------------------------------------
✨DONE✨
 🏂 yao 
```

**Comment by trheyi** [comment]
cat .env， 检查下 .env 的配置。 从命令返回结果上看还是 sqlite

**Comment by tw93** [comment]
``` 
🏂 yao cat .env

YAO_ENV=development # development | production
YAO_ROOT="/Users/tw93/www/yao"
YAO_HOST="0.0.0.0"
YAO_PORT="5099"
YAO_SESSION="memory"
YAO_LOG="/Users/tw93/www/yao/logs/application.log"
YAO_LOG_MODE="TEXT"  #  TEXT | JSON
YAO_JWT_SECRET="bLp@bi!oqo-2U+hoTRUG"
YAO_DB_DRIVER=sqlite3 # sqlite3 | mysql 
YAO_DB_PRIMARY="/Users/tw93/www/yao/db/yao.db"
```

@trheyi

**Comment by feitas** [comment]
2022/11/26 15:54:19 [Recovery] 2022/11/26 - 15:54:19 panic recovered:
runtime error: invalid memory address or nil pointer dereference
/Users/runner/hostedtoolcache/go/1.19.2/x64/src/runtime/panic.go:260 (0x100050895)
/Users/runner/hostedtoolcache/go/1.19.2/x64/src/runtime/signal_unix.go:835 (0x100050865)
/Users/runner/work/yao/gou/model.go:170 (0x100c4ed3b)
/Users/runner/work/yao/yao/setup/install.go:290 (0x100f8dc73)
/Users/runner/work/yao/yao/setup/install.go:100 (0x100f8c74b)
/Users/runner/work/yao/yao/setup/handler.go:75 (0x100f8a614)
/Users/runner/go/pkg/mod/github.com/gin-gonic/gin@v1.7.7/context.go:168 (0x1005ace41)
/Users/runner/go/pkg/mod/github.com/gin-gonic/gin@v1.7.7/recovery.go:99 (0x1005ace2c)
/Users/runner/go/pkg/mod/github.com/gin-gonic/gin@v1.7.7/context.go:168 (0x100f8e33a)
/Users/runner/work/yao/yao/setup/setup.go:57 (0x100f8e1be)
/Users/runner/go/pkg/mod/github.com/gin-gonic/gin@v1.7.7/context.go:168 (0x1005ab050)
/Users/runner/go/pkg/mod/github.com/gin-gonic/gin@v1.7.7/gin.go:555 (0x1005aacb8)
/Users/runner/go/pkg/mod/github.com/gin-gonic/gin@v1.7.7/gin.go:511 (0x1005aa7f1)
/Users/runner/hostedtoolcache/go/1.19.2/x64/src/net/http/server.go:2947 (0x10036aa2b)
/Users/runner/hostedtoolcache/go/1.19.2/x64/src/net/http/server.go:1991 (0x100365c46)
/Users/runner/hostedtoolcache/go/1.19.2/x64/src/runtime/asm_amd64.s:1594 (0x10006c540)

安装配置的时候，数据库选择的是mysql，点击对号就有如上报错。

**Comment by MatrixAge** [comment]
init已弃用
